go_binary(
    name = "example",
    srcs = ["main.go"],
    deps = [
        "//example/lib",
        "//example/third_party/go/github.com/pkg:errors",
        "//example/third_party/go/github.com/sirupsen:logrus",
        "//example/third_party/go/logur.dev/adapter:logrus",
        "//example/third_party/go/logur.dev:logur",
    ],
)
