go_binary(
    name = "gotestxgen",
    srcs = ["main.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//pkg/golist",
        "//pkg/modgraph",
        "//third_party/go:github.com__bazelbuild__buildtools__build",
    ],
)
