go_compile(
    name = "liba",
    import_path = "github.com/sagikazarmark/please-go-modules/example2/liba",
    srcs = glob(["*.go"]),
    go_srcs = glob(["*.go"]),
    deps = ["//example2/libb"],
    visibility = ["PUBLIC"],
)
