filegroup(
    name = "build_defs",
    srcs = [
        "binary.build_defs",
        "go_module.build_defs",
    ],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "go_module",
    srcs = [
        "go_module.build_defs",
    ],
    visibility = ["PUBLIC"],
)
