filegroup(
    name = "build_defs",
    srcs = [
        "binary.build_defs",
        "go_module.build_defs",
    ],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "dist",
    srcs = [
        "go_module.build_defs",
        "config_rules.build_defs",
    ],
    visibility = ["PUBLIC"],
)
