go_library(
    name = "modgraph",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    visibility = ["PUBLIC"],
    deps = [
        "//pkg/golist",
        "//pkg/sumfile",
    ],
)
